### ISSUE TITLE
POST method problem

### ISSUE THREAD

**Issue by cyclone200** [IanLunn/AJAX-Search-Suggest--WeAreHunted.com-Style-#1]
Hi,

I managed to use the Suggest form with a database. If I have something to search like "AJAX Search" ; If I write "AJAX" it will work but if I write "Search" it will not work...

Do you know how to fix that?

Thank you for your help.

**Comment by IanLunn** [comment]
Sorry, that goes outside the scope of the tutorial/demo so not able to provide code. If you are using MySQL to query the database, I imagine using the `LIKE` clause would make suggests that are similar rather than exact: http://www.tutorialspoint.com/mysql/mysql-like-clause.htm

Good luck!

**Comment by cyclone200** [comment]
In fact, I am using the LIKE clause. When I'm testing the script without the field (by simulating a POST request), it works well but when I do it with the form fields, it doesn't work...

Anyway, thank you for your answer.

Best,
