### ISSUE TITLE
Count the number of characters in the query

### ISSUE THREAD

**Issue by cyclone200** [IanLunn/AJAX-Search-Suggest--WeAreHunted.com-Style-#2]
Hi,

You form works very well but I just ask this question to have a better understanding of the code.

I don't see why you count the characters in the query with : 

```
$latestQueryLength = strlen($latestQuery); //count the number of characters in that query
```

And then do this verification : 

```
if (substr(strtolower($name),0,$latestQueryLength) == strtolower($latestQuery))
```

Without this, it still works well.

And if I keep this verification, the LIKE in the Database Query doesn't work anymore.

Thank you for your explanation.

Best regards.

**Comment by IanLunn** [comment]
Honestly, it has been a long time since I looked at this so maybe it's best you read the tutorial: http://ianlunn.co.uk/articles/ajax-search-suggest-wearehunted/

**Comment by cyclone200** [comment]
Of course, I've read the tutorial but it doesn't explain why...

Thank you for your answer.
